services:
    t_boileau.form_handler.manager_factory:
        class: TBoileau\Bundle\FormHandlerBundle\Factory\ManagerFactory
        autowire: true

    TBoileau\Bundle\FormHandlerBundle\Manager\HandlerManager:
        autowire: true

    TBoileau\Bundle\FormHandlerBundle\Factory\ManagerFactoryInterface: '@t_boileau.form_handler.manager_factory'

    t_boileau.form_handler.config:
        class: TBoileau\Bundle\FormHandlerBundle\Config\HandlerConfig
        arguments:
            -

    TBoileau\Bundle\FormHandlerBundle\Config\HandlerConfigInterface: '@t_boileau.form_handler.config'

    TBoileau\Bundle\FormHandlerBundle\Manager\HandlerManagerInterface: '@TBoileau\Bundle\FormHandlerBundle\Manager\HandlerManager'
